### ISSUE TITLE
Changes in Backend Go code ('db' package)

### ISSUE THREAD

**Issue by itsmeabhishek03** [PradyumnaKrishna/enigma-protocol#101]
Hey @PradyumnaKrishna have made a few suggestions for improvements in your go code -

1)QueryRow instead of Query: We can used QueryRow instead of Query in the GetPublicKey function since you're expecting only one row. This simplifies the code and is more efficient.

2)Named Return Values:  i can modify the NewConn function to use named return values. This makes it clear what the function is returning and improves code readability.

3)Consistent Error Return: I can modified the SaveUser function to return an error. This ensures that you can handle errors in the calling code, providing a more robust implementation.

4)Error Handling: I can add error handling throughout the code. It's essential to handle errors appropriately to prevent unexpected crashes and to provide meaningful error messages.

These changes aim to enhance the reliability, clarity, and maintainability of the codebase. Please review and let me know if any further adjustments are needed. Also, please assign this issue under codepeak'23.

**Comment by PradyumnaKrishna** [comment]
Sure you're welcome to contribute.
