### ISSUE TITLE
New UI for the Client side

### ISSUE THREAD

**Issue by Zeus2480** [PradyumnaKrishna/enigma-protocol#13]
I want to design new UI for the client side please assign me this issue under GSSoC'23.

**Comment by PradyumnaKrishna** [comment]
Thanks @Zeus2480, I think this project needs a new UI but this issue seems a big one. I guess we can split this issue and work on multiple smaller components to revamp the client.

If possible please form a plan @Zeus2480 before starting.

**Comment by PradyumnaKrishna** [comment]
@Zeus2480 are you still interested in this issue?
