### ISSUE TITLE
Add Contact Us Section and Update the Docs Section

### ISSUE THREAD

**Issue by aditya9277** [PradyumnaKrishna/enigma-protocol#15]
As it is a open-source project, having a GitHub repository link should be there on the website which is currently missing
I can add many more things in the Docs section, Docs also play a imp role, We can add how it works in a more detailed way by using flowcharts, images etc, So a visitor can understand the project and website.

**Comment by aditya9277** [comment]
i am GSSoC 23 Contributor, i want to work on this, i have already planned for it, Please assign this to me @PradyumnaKrishna

**Comment by PradyumnaKrishna** [comment]
Sure @aditya9277!
