### ISSUE TITLE
Additing contribution.md 

### ISSUE THREAD

**Issue by harshsingh32** [PradyumnaKrishna/enigma-protocol#16]
I would like to add contribution.md in the project, It would like to add some features and make it more expressive and engaging with the users.

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23

**Comment by PradyumnaKrishna** [comment]
@harshsingh32, sure you can add it.

**Comment by PradyumnaKrishna** [comment]
Ping here @shanvijha30, and I will assign it to you.

**Comment by shanvijha30** [comment]
@PradyumnaKrishna I would like to work on this issue.
Could you please assign it to me.
