### ISSUE TITLE
Breakdown of long text message.

### ISSUE THREAD

**Issue by PradyumnaKrishna** [PradyumnaKrishna/enigma-protocol#20]
**Description**
I found the text doesn't sends and breaks when we send a long text message. First part is to look for the problem. I guess the issue is encryption can't encrypt large payload. It may be the limitation of RSA algorithm.

**Possible Solution**
There can be a numerous solutions.
1. First solution is split the text, encrypt it and send it in a sequence one by one. But the problem if a payload gets lost or sequence order mismatch then its hard to decrypt.
2. (preferred) Modify the encryption algorithm, use of both symmetric and asymmetric keys. You can take a reference from https://www.sitepoint.com/encrypt-large-messages-asymmetric-keys-phpseclib/ for the encryption algorithm.
   We use node-forge API for generating cryptographic keys, we can use AES-256 as a symmetric key.

If you have another solution, feel free to share.

**Comment by resonating-homesh** [comment]
@PradyumnaKrishna I would like to try working on this issue as a part of GSSOC '23. Please assign it to me.

**Comment by resonating-homesh** [comment]
Also, I would like to know what is the current limit for text messages to be sent?

**Comment by Sukhendu2002** [comment]
@PradyumnaKrishna, Can you please assign this to me

**Comment by resonating-homesh** [comment]
Is there any different channel to ask for to get issues assigned @PradyumnaKrishna ?

**Comment by PradyumnaKrishna** [comment]
> Is there any different channel to ask for to get issues assigned @PradyumnaKrishna ? 

No, He got it assigned from other issue.

**Comment by PradyumnaKrishna** [comment]
Need any help @Sukhendu2002?

**Comment by Sukhendu2002** [comment]
It will be completed by EOD
