### ISSUE TITLE
Breakdown client into components

### ISSUE THREAD

**Issue by PradyumnaKrishna** [PradyumnaKrishna/enigma-protocol#37]
**Description**
Client is build with Vue.js that has support uses modular approach like Vue components. Currently, the client is a one big Vue file that contains all code.
What I am thinking is to rebuild the complete client side using components, there can be two approaches.
- Create a new frontend from scratch.
- Convert the frontend into components one by one.

Interested contributors comment your approach to solve this issue. This is a one big issue, I will split it into many minor issues so that many contributors can contribute to it.

**Comment by PradyumnaKrishna** [comment]
closes #13 closes #17 and closes #25 as a parent issue.

**Comment by Selwan7131** [comment]
Hello, I would like to work on this issue under GSSoC'23 I would like to follow the approach of rebuilding the front end from scratch.

**Comment by Selwan7131** [comment]
When I run the application and navigate to the chat route I get a buffer error is that normal? Do you have any idea how to fix it

**Comment by srivastavas07** [comment]
Hello, I would like to work on this issue under GSSoC'23

**Comment by Selwan7131** [comment]
I want to contribute to this problem!

**Comment by PradyumnaKrishna** [comment]
Sure @DEEKSHACodeaim, I will assign this to you as well.

**Comment by DEEKSHACodeaim** [comment]
@PradyumnaKrishna Can you explain as to what is left in this and you expect me to work on in particular that will help me be more focussed. Thankyou

**Comment by PradyumnaKrishna** [comment]
> @PradyumnaKrishna Can you explain as to what is left in this and what you expect me to work on in particular that will help me be more focussed. Thankyou

I will provide you more details on this in a few days.

**Comment by PradyumnaKrishna** [comment]
I have created #78 that creates a messageForm component taking reference from https://github.com/alamorre/react-chat-engine-pretty/blob/master/src/components/MessageForm.tsx.

We can create more components like this that will have different properties.
Look at this there are more components that we can include.
https://github.com/alamorre/react-chat-engine-pretty/tree/master/src/components

I am looking to get new components that are:
- [x] MessageForm
- [ ] Alert Component (For notification that will have a cross button)
- [ ] Chat List Header (That will list chats)
- [ ] Chat Messages
- [ ] Chat Card (Sub component of Chat List Header)
- [ ] Chat Header
- [ ] User Info

@DEEKSHACodeaim if you have any question feel free to ask, I will provide help.

**Comment by DEEKSHACodeaim** [comment]
Please give me a week's time and I will update my progress to you. Thank you for assigning this task to me. I will contact you if I need further guidance

**Comment by DEEKSHACodeaim** [comment]
Also could you please add the gssoc '23 and level labels. Thanks

**Comment by PradyumnaKrishna** [comment]
@DEEKSHACodeaim
The alert component is #79 and already assigned, you are welcome to add another component. If you want I can create a separate issue for a component and assign it to you.

**Comment by DEEKSHACodeaim** [comment]
Ok, I will not work on the alert component then, I'll work on other components you had listed like the Chat List Header, chat Messages, etc. After I'm done with either I'll let you know if I can work on another as well. Could please tell me what level this issue comes under though?

**Comment by Nishitbaria** [comment]
> I have created #78 that creates a messageForm component taking reference from https://github.com/alamorre/react-chat-engine-pretty/blob/master/src/components/MessageForm.tsx.
> 
> We can create more components like this that will have different properties. Look at this there are more components that we can include. https://github.com/alamorre/react-chat-engine-pretty/tree/master/src/components
> 
> I am looking to get new components that are:
> 
> * [x]  MessageForm
> * [ ]  Alert Component (For notification that will have a cross button)
> * [ ]  Chat List Header (That will list chats)
> * [ ]  Chat Messages
> * [ ]  Chat Card (Sub component of Chat List Header)
> * [ ]  Chat Header
> * [ ]  User Info
> 
> @DEEKSHACodeaim if you have any question feel free to ask, I will provide help.

@PradyumnaKrishna  which component  are remaining that i can work on please assign me

**Comment by DEEKSHACodeaim** [comment]
@Nishitbaria I am working on the Chat and user components

**Comment by Nishitbaria** [comment]
@DEEKSHACodeaim ,multiple pr will be made for this ,so dont worry

**Comment by DEEKSHACodeaim** [comment]
@Nishitbaria you can definitely work on others, just wanted to let you know the ones I'm working on and assigned to me

**Comment by PradyumnaKrishna** [comment]
`Alert` and `MessageForm` components are completed.

**Comment by Nishitbaria** [comment]
@PradyumnaKrishna ,Which component are remainning which i can work?

**Comment by Goheljay** [comment]
Hey, @PradyumnaKrishna
I want to contribute in this project under hacktoberfest. Can you tell me if there is any component left that I can work on?

**Comment by PradyumnaKrishna** [comment]
Thanks @Goheljay for your interest in this issue.

Yeah, you can work on user-info card, where username is located and a input for start a chat.
Other component would be chat list and chat card, you can work on any of them.
<img width="385" alt="Screenshot 2023-10-01 at 10 04 29" src="https://github.com/PradyumnaKrishna/enigma-protocol/assets/51270439/3d2ec5c3-7daf-4444-bcdb-4db4a45c53e5">

**Comment by Tizzz-555** [comment]
Hi @PradyumnaKrishna I am also interested in contributing, can I pick a component?

**Comment by PradyumnaKrishna** [comment]
Welcome @Tizzz-555, This is the list of unimplemented components till now, you are welcome to add any.

* [ ]  Chat List Header (That will list chats)
* [ ]  Chat Messages
* [ ]  Chat Card (Sub component of Chat List Header)
* [ ]  Chat Header
* [ ]  User Info

**Comment by tara-matthew** [comment]
Hey! Would I be able to work on one of these components?

**Comment by PradyumnaKrishna** [comment]
> Hey! Would I be able to work on one of these components?

You're welcome to contribute to any of these components.

**Comment by tara-matthew** [comment]
Are you planning on using atomic design at all? It might make sense to start with atoms if so. I'd guess that the Chat Header is an atom?

**Comment by PradyumnaKrishna** [comment]
Sure @tara-matthew, you are welcome to create another issue for that and I will assign it to you.

**Comment by tara-matthew** [comment]
Fantastic, thank you! I've decided to go for the Chat Card having looked through the code. I'll get working on this tomorrow 🚀

**Comment by PradyumnaKrishna** [comment]
Chat card is just a button for now, I am thinking to make it more than a button. It will show user id and the last message. So, We require a component that contains user id and the last message, and that I call chat card.

We will pass the following props to the chat card component.
- userId : user id to show in the card
- description : the last message
- isActive : Boolean that makes it active or active its style
- onClick : Function that will execute on click

**Comment by Tizzz-555** [comment]
@PradyumnaKrishna What is the MessageForm component doing? It seems like is not used anywhere. 
I was thinking of doing the Chat Messages component, but I would like to understand better what the MessageForm is

**Comment by PradyumnaKrishna** [comment]
> @PradyumnaKrishna What is the MessageForm component doing?
Ah I just didn't added it to the chat UI, you can create a PR adding it to the chat window or work on the chat messages. Two PRs
