### ISSUE TITLE
Hint text not visible 

### ISSUE THREAD

**Issue by ydv-ankit** [PradyumnaKrishna/Enigma-Protocol#44]
issue: Input box of adding other user's id have very low visibility of hint text

![p1](https://github.com/PradyumnaKrishna/enigma-protocol/assets/85311495/35a4f0ab-3de1-4dbc-a276-fef54502c623)

It can be corrected by using different and more brighter color

**Comment by techmannih** [comment]
Hii @PradyumnaKrishna @ydv-ankit ,
I'll handle this issue.. please assign me the same

**Comment by ydv-ankit** [comment]
Yes, can you assign to me?
