### ISSUE TITLE
[Feature]: Validation and Toast message

### ISSUE THREAD

**Issue by 777Prabhjot** [PradyumnaKrishna/enigma-protocol#79]
There is no validation for other user's id field it should be validated on front-end so that user don't able to made request to the server for a blank input value. and a beautiful toast message should be appear for error message rather than a regular javascript alert message.

**To Reproduce**

1. Go to chat page
2. Click on add button
3. There is no front-end validation
4. And the alert message is not looking good

**Screen Shot**

https://github.com/PradyumnaKrishna/enigma-protocol/assets/68184118/91001753-0630-48fa-8b0b-aefd51c9ee64

### I would love to work on this

**Comment by PradyumnaKrishna** [comment]
Sure you are welcome to add a component for this, with #37.
