### ISSUE TITLE
Make Chat Card component

### ISSUE THREAD

**Issue by tara-matthew** [PradyumnaKrishna/enigma-protocol#84]
As part of https://github.com/PradyumnaKrishna/enigma-protocol/issues/37 separate the Chat Card into its own component.

**Comment by PradyumnaKrishna** [comment]
Assigned @tara-matthew.

**Comment by tara-matthew** [comment]
I'm all ready to submit a PR, please could you add the Hacktoberfest label so this will count towards that?

**Comment by PradyumnaKrishna** [comment]
Added the label.
