### ISSUE TITLE
Add linting on the frontend

### ISSUE THREAD

**Issue by tara-matthew** [PradyumnaKrishna/enigma-protocol#85]
The project could benefit from a linter being added on the frontend to enforce coding standards - ie [ESLint](https://eslint.org/). 

I will pick up this issue after the one I currently have in progress if you're happy for me to.

**Comment by PradyumnaKrishna** [comment]
This has been on my card, thank you for creating this issue.

**Comment by tara-matthew** [comment]
Perfect, I'll get working on this today! 🚀

**Comment by PradyumnaKrishna** [comment]
Completed with #88.
