### ISSUE TITLE
Make Chat List Header Component

### ISSUE THREAD

**Issue by Tizzz-555** [PradyumnaKrishna/enigma-protocol#87]
This is part of #37, will separate the chat header into its own component.

**Comment by PradyumnaKrishna** [comment]
Assigned @Tizzz-555, Feel free to ask if have any question.

We will provide a list of users as prop to this header, which will include chat card and it will emit `switch` with the `userId`.

**Comment by Tizzz-555** [comment]
Yeah, I will mostly have time to work on this in the weekend, I will keep you updated ;)
