### ISSUE TITLE
Run ESLint

### ISSUE THREAD

**Issue by tara-matthew** [PradyumnaKrishna/enigma-protocol#89]
Once ESLint has been added, run the linter using the rules which have been set up

**Comment by tara-matthew** [comment]
@PradyumnaKrishna Any chance I could get the Hacktoberfest label on this? No worries if not, I'll get this done later today 👌

**Comment by ashmit-coder** [comment]
Hey @PradyumnaKrishna can you resolve this issue just to reduce the clatter in issues tab
