### ISSUE TITLE
Make User Info Component

### ISSUE THREAD

**Issue by Tizzz-555** [PradyumnaKrishna/enigma-protocol#91]
This is part of https://github.com/PradyumnaKrishna/enigma-protocol/issues/37, will separate the user info into its own component.

**Comment by PradyumnaKrishna** [comment]
Go ahead @Tizzz-555

**Comment by Tizzz-555** [comment]
@PradyumnaKrishna Would you like me adding a copy icon to the right of the userId to better signal that the id is copyable on click?

**Comment by PradyumnaKrishna** [comment]
Yes add it.

**Comment by Tizzz-555** [comment]
@PradyumnaKrishna Can you kindly explain to me how would you like the style to be handled across components? I see there is a scoped attribute in Chat.vue that prevents the styles to propagate to components, is this the design you prefer?
Would that mean copying the relevant css from Chat.vue to the component we are working on?

**Comment by PradyumnaKrishna** [comment]
I am not sure about the style either, make it the way you like to.
