### ISSUE TITLE
Error when opening a chat with an expired cookie 

### ISSUE THREAD

**Issue by Tizzz-555** [PradyumnaKrishna/enigma-protocol#92]
In the list of my chats, I have 4 chats now, 3 that I just created today and 1 that has been automatically saved from a previous session. This last one crashes the app with this error when clicked:
![Screenshot 2023-10-11 at 10 11 37](https://github.com/PradyumnaKrishna/enigma-protocol/assets/103275021/7057e8d2-9d3e-4442-86d0-1bd1c4988b27)

[Here](https://github.com/PradyumnaKrishna/enigma-protocol/blob/9e0a66b9a630e90de1548ea2c41e48d7ca559f26/client/src/views/Chat.vue#L218) we crash if given an invalid key.
Our expired chat doesn't have a cookie associated with it anymore, therefore its `publicKey` value is `null`.
![Screenshot 2023-10-11 at 11 03 29](https://github.com/PradyumnaKrishna/enigma-protocol/assets/103275021/b9c9b1f0-b0c6-4384-a618-89683997ada2)

### 1. Graceful Error Handling:
Before using the publicKey in any operations, check if it's valid. If it's not valid (e.g., null or not a string), handle the error gracefully:
```js 
if (!publicKey || typeof publicKey !== 'string') {
    console.error('Invalid publicKey for user:', this.to);
    this.toastmsg = "Error: Invalid chat session.";
    this.toastType = "error";
    setTimeout(() => {
        this.toastmsg = "";
        this.toastType = "";
    }, 2000);
    return;
} 
```

### 2. Cleanup or Repair:
When loading the chat list, cross-check each chat session with the cookies. If a chat session doesn't have an associated cookie (or the cookie has an invalid value), remove it from the chat list.
```js
this.users = this.users.filter(user => {
    const publicKey = this.$cookies.get(user);
    return publicKey && typeof publicKey === 'string';
});
```

**Comment by PradyumnaKrishna** [comment]
Thank you for reporting this issue, let me think about it.

**Comment by Tizzz-555** [comment]
Sure thing! Let me know 🙏

**Comment by Tizzz-555** [comment]
@PradyumnaKrishna Were you able to check this out? Can you replicate the bug on your end? I worked on it a bit yesterday and found a workaround, I would like to show you

**Comment by PradyumnaKrishna** [comment]
> @PradyumnaKrishna Were you able to check this out? Can you replicate the bug on your end? I worked on it a bit yesterday and found a workaround, I would like to show you

Yeah sure show me.

**Comment by PradyumnaKrishna** [comment]
I was thinking what if the client can verify all the public keys and users, when the browsers loads the chat.
Or, verify the public key and user when someone open the that chat.
