### ISSUE TITLE
Enhance messenger app UI/UX for better user experience

### ISSUE THREAD

**Issue by ydvmudit07** [PradyumnaKrishna/enigma-protocol#97]
### _The current UI of this end-to-end encrypted messenger app is functional but minimal. For Hacktoberfest, I would like to contribute improvements to create a more engaging and intuitive user experience._

**_Some ideas:_**

- Implement interactive animations and transitions for visual appeal
- Use color, typography, and whitespace strategically for better aesthetics
- Streamline flows to make key actions more discoverable
- Ensure UI adapts smoothly across device sizes and platforms
- Improve information hierarchy and layout for clearer focus
- Declutter interface and refine visuals for cleaner look

_As an experienced front-end developer, I'm excited to make the UI more polished, playful, and user-friendly. @PradyumnaKrishna I'm happy to contribute these UX/UI enhancements if this issue is tagged for Hacktoberfest and assigned to me. Let me know if you have any other ideas for improving the user experience!_

---------------------------------------------------------------------------------------------------------------------------------------

![Screenshot 2023-10-23 112223](https://github.com/PradyumnaKrishna/enigma-protocol/assets/120110061/8979179a-fe77-4531-9f98-b7af90294b43)
![Screenshot 2023-10-23 112238](https://github.com/PradyumnaKrishna/enigma-protocol/assets/120110061/5b57c1a8-5865-4d3c-b7ba-2305f74ca65a)
![Screenshot 2023-10-23 112250](https://github.com/PradyumnaKrishna/enigma-protocol/assets/120110061/4eb7886d-ecab-48b4-a1d5-6a61b48e60cc)

**Comment by ydvmudit07** [comment]
@PradyumnaKrishna _kindly review this issue, and assign it to me under **Hacktoberfest.**_

**Comment by PradyumnaKrishna** [comment]
I am thinking to remove docs and home from the client, I will move the docs to static site generator. You are welcome to update the chat UI.

**Comment by ydvmudit07** [comment]
_Sure, I'll then start working on chat UI_.
